---
- name: Check Disk Space Usage
  hosts: vag
  tasks:
          - name: Disk usage from command module
            command: df -h
            register: space
          - debug:
                  var: space.stdout_lines
